---
- name: upload shorewall defaults
  template:
    src: etc/default/shorewall.j2
    dest: /etc/default/shorewall
    owner: root
    group: root
    mode: 0644

- name: upload shorewall configuration
  template:
    src: etc/shorewall/shorewall.conf.j2
    dest: /etc/shorewall/shorewall.conf
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall zones-file
  template:
    src: etc/shorewall/zones.j2
    dest: /etc/shorewall/zones
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall interfaces-file
  template:
    src: etc/shorewall/interfaces.j2
    dest: /etc/shorewall/interfaces
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall policy-file
  template:
    src: etc/shorewall/policy.j2
    dest: /etc/shorewall/policy
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall masquerade-file
  template:
    src: etc/shorewall/masq.j2
    dest: /etc/shorewall/masq
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall rules-file
  template:
    src: etc/shorewall/rules.j2
    dest: /etc/shorewall/rules
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall
