- name: import vars/shorewall/{{ hostname_item }}.yml from playbook if present
  include_vars: vars/shorewall/{{ hostname_item }}.yml
  failed_when: no
  ignore_errors: yes
  register: config_in_playbook
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname_short }}"
  loop_control:
    loop_var: hostname_item

- name: merge in imported variables if found
  set_fact:
    shorewall_zones: "{{ shorewall_zones + shorewall_extra_zones | default([]) }}"
    shorewall_interfaces: "{{ shorewall_interfaces + shorewall_extra_interfaces | default([]) }}"
    shorewall_policies: "{{ shorewall_extra_policies | default([]) + shorewall_policies }}"
    shorewall_masquerade: "{{ shorewall_masquerade + shorewall_extra_masquerade | default([]) }}"
    shorewall_rules: #"{{ shorewall_rules + shorewall_extra_rules | default([]) }}"
      ALL: "{{ shorewall_rules.ALL + shorewall_extra_rules.ALL | default([]) }}"
      ESTABLISHED: "{{ shorewall_rules.ESTABLISHED + shorewall_extra_rules.ESTABLISHED | default([]) }}"
      RELATED: "{{ shorewall_rules.RELATED + shorewall_extra_rules.RELATED | default([]) }}"
      INVALID: "{{ shorewall_rules.INVALID + shorewall_extra_rules.INVALID | default([]) }}"
      UNTRACKED: "{{ shorewall_rules.UNTRACKED + shorewall_extra_rules.UNTRACKED | default([]) }}"
      NEW: "{{ shorewall_rules.NEW + shorewall_extra_rules.NEW | default([]) }}"

- name: upload shorewall defaults
  template:
    src: etc/default/shorewall.j2
    dest: /etc/default/shorewall
    owner: root
    group: root
    mode: 0644

- name: upload shorewall configuration
  template:
    src: etc/shorewall/shorewall.conf.j2
    dest: /etc/shorewall/shorewall.conf
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall zones-file
  template:
    src: etc/shorewall/zones.j2
    dest: /etc/shorewall/zones
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall interfaces-file
  template:
    src: etc/shorewall/interfaces.j2
    dest: /etc/shorewall/interfaces
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall policy-file
  template:
    src: etc/shorewall/policy.j2
    dest: /etc/shorewall/policy
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall masquerade-file
  template:
    src: etc/shorewall/masq.j2
    dest: /etc/shorewall/masq
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall tunnels-file
  template:
    src: etc/shorewall/tunnels.j2
    dest: /etc/shorewall/tunnels
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall

- name: upload shorewall rules-file
  template:
    src: etc/shorewall/rules.j2
    dest: /etc/shorewall/rules
    owner: root
    group: root
    mode: 0640
  notify: restart shorewall
