---
- include: "{{ distro_installer }}"
  with_first_found:
    - "install/{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
    - "install/{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: distro_installer
  tags:
    - install

- include: configure.yml
  tags:
    - configure
